baseURL = 'https://fikri.pages.dev/'
title = 'Mahasemesta'

[markup.goldmark.renderer]
unsafe = true

disableKinds = [ "taxonomy", "taxonomyTerm", "RSS", "robotsTXT", "sitemap" ]

[params]
keywords = "mahasemesta, semesta, oracle, spiritual"
author = "Fikri Azhar Novianto"